'CalMeasures'[Total_Actual_Revenue] =
SUMX(
    FILTER( NFData, NFData[Revenue/Expenses] = "Revenues" ),
    NFData[Actual Amount]
)

'CalMeasures'[Total_Budgeted_Revenue] =
SUMX(
    FILTER( NFData, NFData[Revenue/Expenses] = "Revenues" ),
    NFData[Budget Amount]
)

'CalMeasures'[%_Efficiency_Revenue] =
DIVIDE( [Total_Actual_Revenue], [Total_Budgeted_Revenue] )

'CalMeasures'[Total_Actual_Expenses] =
SUMX(
    FILTER( NFData, NFData[Revenue/Expenses] = "Expenses" ),
    NFData[Actual Amount]
)

'CalMeasures'[Total_Budgeted_Expenses] =
SUMX(
    FILTER( NFData, NFData[Revenue/Expenses] = "Expenses" ),
    NFData[Budget Amount]
)

'CalMeasures'[%_Efficiency_Expenses] =
DIVIDE( [Total_Actual_Expenses], [Total_Budgeted_Expenses] )
